#!/usr/bin/env python3
"""Generate term cross-reference report for the Tamil AI Glossary book.

Scans book chapters for term entries (**English — Tamil**) and produces
a markdown report with per-chapter counts, duplicate detection, and
glossary coverage analysis.

Usage:
    python3 scripts/gen-term-xref.py
"""

import re
import os

BOOK_DIR = os.path.join(os.path.dirname(__file__), '..', 'book')
GLOSSARY = os.path.join(os.path.dirname(__file__), '..', 'ai-tamil-glossary.md')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'llm-context', 'term-xref.md')

CHAPTER_NAMES = {
    '01-ai-foundations': 'AI Foundations',
    '02-machine-learning': 'Machine Learning',
    '03-neural-networks': 'Neural Networks',
    '04-training-optimization': 'Training & Optimization',
    '05-transformers-language-models': 'Transformers & Language Models',
    '06-nlp-text-processing': 'NLP & Text Processing',
    '07-embeddings-search': 'Embeddings & Search',
    '08-prompting-interaction': 'Prompting & Interaction',
    '09-agents-tools': 'Agents & Tools',
    '10-safety-ethics-evaluation': 'Safety, Ethics & Evaluation',
    '11-appendix-computing-infra': 'Appendix — Computing & Infra',
}


def scan_book_terms():
    """Scan book chapters and return term data."""
    chapters = {}
    all_terms = {}  # eng_term -> [(chapter_id, line, tamil)]

    for fname in sorted(os.listdir(BOOK_DIR)):
        if not re.match(r'\d{2}-', fname) or not fname.endswith('.md'):
            continue
        ch_id = fname.replace('.md', '')
        filepath = os.path.join(BOOK_DIR, fname)
        terms = []
        with open(filepath, 'r', encoding='utf-8') as f:
            for lineno, line in enumerate(f, 1):
                m = re.match(r'^\*\*([A-Z][^—*]+)—\s*([^*]+)\*\*', line)
                if m:
                    eng = m.group(1).strip()
                    tam = m.group(2).strip()
                    terms.append((lineno, eng, tam))
                    all_terms.setdefault(eng, []).append((ch_id, lineno, tam))
        chapters[ch_id] = terms

    return chapters, all_terms


def scan_glossary_terms():
    """Scan ai-tamil-glossary.md for all defined terms."""
    terms = set()
    if not os.path.exists(GLOSSARY):
        return terms
    with open(GLOSSARY, 'r', encoding='utf-8') as f:
        for line in f:
            m = re.match(r'^\|\s*([A-Z][^|]+)\|', line)
            if m:
                terms.add(m.group(1).strip())
    return terms


def generate_report(chapters, all_terms, glossary_terms):
    """Generate the markdown report."""
    lines = []
    lines.append('# Term Cross-Reference Report')
    lines.append('')
    lines.append('Auto-generated by `scripts/gen-term-xref.py`. Do not edit manually.')
    lines.append('')

    # --- Summary ---
    total = sum(len(v) for v in chapters.values())
    unique = len(all_terms)
    dupes = {k: v for k, v in all_terms.items() if len(v) > 1}

    lines.append('## Summary')
    lines.append('')
    lines.append(f'- **Total term entries across all chapters:** {total}')
    lines.append(f'- **Unique terms:** {unique}')
    lines.append(f'- **Duplicate terms (in 2+ chapters):** {len(dupes)}')
    lines.append(f'- **Glossary terms (ai-tamil-glossary.md):** {len(glossary_terms)}')
    lines.append('')

    # --- Per-chapter counts ---
    lines.append('## Per-Chapter Term Count')
    lines.append('')
    lines.append('| Chapter | Name | Terms |')
    lines.append('|---------|------|------:|')
    for ch_id, terms in chapters.items():
        name = CHAPTER_NAMES.get(ch_id, ch_id)
        lines.append(f'| {ch_id} | {name} | {len(terms)} |')
    lines.append(f'| | **Total** | **{total}** |')
    lines.append('')

    # --- Duplicates ---
    lines.append('## Duplicate Terms')
    lines.append('')
    if dupes:
        lines.append('Terms defined as full entries in multiple chapters:')
        lines.append('')
        lines.append('| Term | Chapters |')
        lines.append('|------|----------|')
        for term in sorted(dupes.keys()):
            locs = dupes[term]
            ch_list = ', '.join(f'{c} (L{l})' for c, l, _ in locs)
            lines.append(f'| {term} | {ch_list} |')
        lines.append('')
    else:
        lines.append('No duplicates found.')
        lines.append('')

    # --- Glossary coverage ---
    book_eng_terms = set(all_terms.keys())
    in_book_not_glossary = sorted(book_eng_terms - glossary_terms)
    in_glossary_not_book = sorted(glossary_terms - book_eng_terms)

    lines.append('## Glossary ↔ Book Coverage')
    lines.append('')
    lines.append(f'### In book but NOT in glossary ({len(in_book_not_glossary)})')
    lines.append('')
    if in_book_not_glossary:
        for t in in_book_not_glossary:
            locs = all_terms[t]
            ch_list = ', '.join(c for c, _, _ in locs)
            lines.append(f'- **{t}** → {ch_list}')
    else:
        lines.append('None.')
    lines.append('')

    lines.append(f'### In glossary but NOT in book ({len(in_glossary_not_book)})')
    lines.append('')
    if in_glossary_not_book:
        for t in in_glossary_not_book:
            lines.append(f'- {t}')
    else:
        lines.append('None.')
    lines.append('')

    # --- Full term list per chapter ---
    lines.append('## Full Term List by Chapter')
    lines.append('')
    for ch_id, terms in chapters.items():
        if not terms:
            continue
        name = CHAPTER_NAMES.get(ch_id, ch_id)
        lines.append(f'### {ch_id} — {name} ({len(terms)} terms)')
        lines.append('')
        lines.append('| # | Line | English | Tamil |')
        lines.append('|--:|-----:|---------|-------|')
        for i, (lineno, eng, tam) in enumerate(terms, 1):
            dupe_marker = ' ⚠️' if len(all_terms.get(eng, [])) > 1 else ''
            lines.append(f'| {i} | {lineno} | {eng}{dupe_marker} | {tam} |')
        lines.append('')

    return '\n'.join(lines)


def main():
    chapters, all_terms = scan_book_terms()
    glossary_terms = scan_glossary_terms()
    report = generate_report(chapters, all_terms, glossary_terms)

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f'✓ Report written to {OUTPUT}')
    print(f'  Chapters: {len(chapters)}')
    print(f'  Total entries: {sum(len(v) for v in chapters.values())}')
    print(f'  Unique terms: {len(all_terms)}')
    dupes = {k: v for k, v in all_terms.items() if len(v) > 1}
    print(f'  Duplicates: {len(dupes)}')


if __name__ == '__main__':
    main()
